export interface Database {
  public: {
    Views: {};
    Functions: {};
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          password_hash: string;
          role: 'admin' | 'analyst' | 'user';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name?: string | null;
          password_hash: string;
          role?: 'admin' | 'analyst' | 'user';
        };
        Update: {
          email?: string;
          name?: string | null;
          password_hash?: string;
          role?: 'admin' | 'analyst' | 'user';
        };
        Relationships: [];
      };
      threats: {
        Row: {
          id: string;
          name: string;
          description: string;
          stride_category: string;
          stride_rationale: string | null;
          threat_source: string;
          affected_components: string[];
          vulnerability: string | null;
          exploit_scenario: string | null;
          likelihood: number;
          likelihood_justification: string | null;
          impact: number;
          impact_justification: string | null;
          severity_score: number;
          risk_rating: string;
          fair_tef: number | null;
          fair_tef_citation: string | null;
          fair_vulnerability: number | null;
          fair_vulnerability_citation: string | null;
          fair_lef: number | null;
          fair_primary_loss_usd: number | null;
          fair_primary_loss_citation: string | null;
          fair_secondary_loss_usd: number | null;
          fair_secondary_loss_citation: string | null;
          fair_ale: number | null;
          remediation_strategies: unknown;
          nist_stage: string;
          rmf_status: string;
          status: string;
          vulnerability_ids: string[];
          related_bips: string[];
          evidence_sources: unknown;
          submitted_by: string | null;
          submitted_by_name: string | null;
          date_identified: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          description: string;
          stride_category: string;
          threat_source: string;
          likelihood: number;
          impact: number;
          stride_rationale?: string | null;
          affected_components?: string[];
          vulnerability?: string | null;
          exploit_scenario?: string | null;
          likelihood_justification?: string | null;
          impact_justification?: string | null;
          fair_tef?: number | null;
          fair_vulnerability?: number | null;
          fair_lef?: number | null;
          fair_primary_loss_usd?: number | null;
          fair_secondary_loss_usd?: number | null;
          fair_ale?: number | null;
          remediation_strategies?: unknown;
          nist_stage?: string;
          rmf_status?: string;
          status?: string;
          vulnerability_ids?: string[];
          related_bips?: string[];
          evidence_sources?: unknown;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          stride_category?: string;
          threat_source?: string;
          likelihood?: number;
          impact?: number;
          stride_rationale?: string | null;
          affected_components?: string[];
          vulnerability?: string | null;
          exploit_scenario?: string | null;
          likelihood_justification?: string | null;
          impact_justification?: string | null;
          fair_tef?: number | null;
          fair_vulnerability?: number | null;
          fair_lef?: number | null;
          fair_primary_loss_usd?: number | null;
          fair_secondary_loss_usd?: number | null;
          fair_ale?: number | null;
          remediation_strategies?: unknown;
          nist_stage?: string;
          rmf_status?: string;
          status?: string;
          vulnerability_ids?: string[];
          related_bips?: string[];
          evidence_sources?: unknown;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
        };
        Relationships: [];
      };
      bip_evaluations: {
        Row: {
          id: string;
          bip_number: string;
          title: string;
          summary: string | null;
          recommendation: string | null;
          necessity_score: number | null;
          threats_addressed: string[];
          mitigation_effectiveness: number | null;
          community_consensus: number | null;
          implementation_readiness: number | null;
          economic_impact: string | null;
          adoption_percentage: number | null;
          bip_status: string;
          status: string;
          submitted_by: string | null;
          submitted_by_name: string | null;
          bip_author: string | null;
          bip_type: string | null;
          bip_layer: string | null;
          last_evaluated_at: string | null;
          evaluation_trigger: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          bip_number: string;
          title: string;
          summary?: string | null;
          recommendation?: string | null;
          necessity_score?: number | null;
          threats_addressed?: string[];
          mitigation_effectiveness?: number | null;
          community_consensus?: number | null;
          implementation_readiness?: number | null;
          economic_impact?: string | null;
          adoption_percentage?: number | null;
          bip_status?: string;
          status?: string;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
          bip_author?: string | null;
          bip_type?: string | null;
          bip_layer?: string | null;
          last_evaluated_at?: string | null;
          evaluation_trigger?: string | null;
        };
        Update: {
          id?: string;
          bip_number?: string;
          title?: string;
          summary?: string | null;
          recommendation?: string | null;
          necessity_score?: number | null;
          threats_addressed?: string[];
          mitigation_effectiveness?: number | null;
          community_consensus?: number | null;
          implementation_readiness?: number | null;
          economic_impact?: string | null;
          adoption_percentage?: number | null;
          bip_status?: string;
          status?: string;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
          bip_author?: string | null;
          bip_type?: string | null;
          bip_layer?: string | null;
          last_evaluated_at?: string | null;
          evaluation_trigger?: string | null;
        };
        Relationships: [];
      };
      fud_analyses: {
        Row: {
          id: string;
          narrative: string;
          category: string;
          validity_score: number | null;
          fud_status: string;
          status: string;
          evidence_for: string[];
          evidence_against: string[];
          debunk_summary: string | null;
          related_threats: string[];
          price_impact_estimate: string | null;
          last_seen: string;
          submitted_by: string | null;
          submitted_by_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          narrative: string;
          category: string;
          validity_score?: number | null;
          fud_status?: string;
          status?: string;
          evidence_for?: string[];
          evidence_against?: string[];
          debunk_summary?: string | null;
          related_threats?: string[];
          price_impact_estimate?: string | null;
          last_seen?: string;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
        };
        Update: {
          id?: string;
          narrative?: string;
          category?: string;
          validity_score?: number | null;
          fud_status?: string;
          status?: string;
          evidence_for?: string[];
          evidence_against?: string[];
          debunk_summary?: string | null;
          related_threats?: string[];
          price_impact_estimate?: string | null;
          last_seen?: string;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
        };
        Relationships: [];
      };
      vulnerabilities: {
        Row: {
          id: string;
          name: string;
          description: string;
          affected_components: string[];
          severity: number;
          exploitability: number;
          vulnerability_score: number;
          vulnerability_rating: string;
          vuln_status: string;
          remediation_strategies: unknown;
          related_bips: string[];
          evidence_sources: unknown;
          status: string;
          submitted_by: string | null;
          submitted_by_name: string | null;
          date_identified: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          description: string;
          affected_components?: string[];
          severity: number;
          exploitability: number;
          vuln_status?: string;
          remediation_strategies?: unknown;
          related_bips?: string[];
          evidence_sources?: unknown;
          status?: string;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
          date_identified?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          affected_components?: string[];
          severity?: number;
          exploitability?: number;
          vuln_status?: string;
          remediation_strategies?: unknown;
          related_bips?: string[];
          evidence_sources?: unknown;
          status?: string;
          submitted_by?: string | null;
          submitted_by_name?: string | null;
        };
        Relationships: [];
      };
      threat_vulnerabilities: {
        Row: {
          threat_id: string;
          vulnerability_id: string;
          created_at: string;
        };
        Insert: {
          threat_id: string;
          vulnerability_id: string;
        };
        Update: {
          threat_id?: string;
          vulnerability_id?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          entity_type: string;
          entity_id: string;
          action: string;
          user_id: string;
          user_name: string;
          diff: unknown;
          created_at: string;
        };
        Insert: {
          entity_type: string;
          entity_id: string;
          action: string;
          user_id: string;
          user_name: string;
          diff?: unknown;
        };
        Update: never;
        Relationships: [];
      };
      votes: {
        Row: {
          id: string;
          target_type: string;
          target_id: string;
          x_id: string;
          x_username: string;
          x_name: string;
          vote_value: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          target_type: string;
          target_id: string;
          x_id: string;
          x_username: string;
          x_name: string;
          vote_value: number;
        };
        Update: {
          target_type?: string;
          target_id?: string;
          x_id?: string;
          x_username?: string;
          x_name?: string;
          vote_value?: number;
        };
        Relationships: [];
      };
      comments: {
        Row: {
          id: string;
          target_type: string;
          target_id: string;
          x_id: string;
          x_username: string;
          x_name: string;
          x_profile_image: string;
          content: string;
          parent_id: string | null;
          likes: number;
          liked_by: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          target_type: string;
          target_id: string;
          x_id: string;
          x_username: string;
          x_name: string;
          x_profile_image: string;
          content: string;
          parent_id?: string | null;
        };
        Update: {
          target_type?: string;
          target_id?: string;
          x_id?: string;
          x_username?: string;
          x_name?: string;
          x_profile_image?: string;
          content?: string;
          parent_id?: string | null;
        };
        Relationships: [];
      };
      reeval_queue: {
        Row: {
          id: string;
          bip_id: string;
          bip_number: string;
          reason: string;
          details: string | null;
          priority: number;
          status: string;
          error_message: string | null;
          attempts: number;
          max_attempts: number;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          bip_id: string;
          bip_number: string;
          reason: string;
          details?: string | null;
          priority?: number;
          status?: string;
          error_message?: string | null;
          attempts?: number;
          max_attempts?: number;
        };
        Update: {
          bip_id?: string;
          bip_number?: string;
          reason?: string;
          details?: string | null;
          priority?: number;
          status?: string;
          error_message?: string | null;
          attempts?: number;
          max_attempts?: number;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      external_signals: {
        Row: {
          id: string;
          source: string;
          external_id: string;
          source_url: string | null;
          title: string;
          description: string | null;
          severity: string | null;
          published_date: string | null;
          related_bips: string[];
          cve_id: string | null;
          processed: boolean;
          threat_id: string | null;
          created_at: string;
        };
        Insert: {
          source: string;
          external_id: string;
          source_url?: string | null;
          title: string;
          description?: string | null;
          severity?: string | null;
          published_date?: string | null;
          related_bips?: string[];
          cve_id?: string | null;
          processed?: boolean;
          threat_id?: string | null;
        };
        Update: {
          source?: string;
          external_id?: string;
          source_url?: string | null;
          title?: string;
          description?: string | null;
          severity?: string | null;
          published_date?: string | null;
          related_bips?: string[];
          cve_id?: string | null;
          processed?: boolean;
          threat_id?: string | null;
        };
        Relationships: [];
      };
      monitoring_runs: {
        Row: {
          id: string;
          pipeline: string;
          status: string;
          started_at: string;
          completed_at: string | null;
          result: unknown;
          error_message: string | null;
        };
        Insert: {
          pipeline: string;
          status: string;
          started_at?: string;
          completed_at?: string | null;
          result?: unknown;
          error_message?: string | null;
        };
        Update: {
          pipeline?: string;
          status?: string;
          started_at?: string;
          completed_at?: string | null;
          result?: unknown;
          error_message?: string | null;
        };
        Relationships: [];
      };
    };
  };
}
